version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/testing"

  - package-ecosystem: "npm"
    directory: "/site/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/documentation"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
    target-branch: "release-1.24"
    ignore:
      - dependency-name: "k8s.io/*"
        versions: [">=0.25.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.24"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/testing"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.24"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
    target-branch: "release-1.23"
    ignore:
      - dependency-name: "k8s.io/*"
        versions: [">=0.24.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.23"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/testing"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.23"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
    target-branch: "release-1.1"
    ignore:
      - dependency-name: "k8s.io/*"
        versions: [">=0.23.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.1"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/testing"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.1"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
    target-branch: "release-1.25"
    ignore:
      - dependency-name: "k8s.io/*"
        versions: [">=0.26.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.25"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/testing"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.25"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
