trigger: none

pool:
  vmImage: ubuntu-18.04

stages:
  - stage: testing
    dependsOn: []
    jobs:
    - job: testing
      timeoutInMinutes: 180
      steps:
        - bash: |
            echo "testing azure pipeline"
          displayName: test pipeline
